### ISSUE TITLE
Wrong XML Tag

### ISSUE THREAD

**Issue by jplinux** [PluginsOCSInventory-NG/crontabTasks#4]
Hi,
There a small mistake between entries mentionned in "perl/Apache/Ocsinventory/Plugins/Crontabtasks/Map.pm" and what the agent sends in its  XML tags.
On the server side, we want entries CRONTABTASKS but we get CRONTAB from the agent. 
I patch the agent module "/usr/share/perl5/vendor_perl/Ocsinventory/Agent/Modules/CronTab.pm" with the following patch:

```
--- /usr/share/perl5/vendor_perl/Ocsinventory/Agent/Modules/CronTab.pm.ori      2021-01-04 12:15:40.073362072 +0100
+++ /usr/share/perl5/vendor_perl/Ocsinventory/Agent/Modules/CronTab.pm  2021-01-04 12:02:18.864324189 +0100
@@ -114,7 +114,7 @@
             $dayofmonth = $_->{_dom};
             $dayofweek = $_->{_dow};
             $month = $_->{_month};
-            push @{$common->{xmltags}->{CRONTAB}},
+            push @{$common->{xmltags}->{CRONTABTASKS}},
             {
                MINUTE => [$minute],
                HOUR => [$hour],
```

**Comment by fbomj** [comment]
Fixed with https://github.com/PluginsOCSInventory-NG/crontabTasks/commit/6e1f1cb39fb163482dd5c3d88bcec1273da6dfd4
